<ul>
    <li>
        View
        <ul>
            <li><a href="<?php echo $this->url('zfcadmin/eportal-school') ?>">School</a></li>
            <li><a href="<?php echo $this->url('zfcadmin/eportal-class') ?>">Class</a></li>
            <li><a href="<?php echo $this->url('zfcadmin/eportal-department') ?>">Department</a></li>
            <li><a href="<?php echo $this->url('zfcadmin/eportal-subject') ?>">Subject</a></li>
            <li><a href="<?php echo $this->url('zfcadmin/eportal-session') ?>">Session</a></li>
            <li><a href="<?php echo $this->url('zfcadmin/eportal-term') ?>">Term</a></li>
        </ul>
    </li>
    <li><a href="<?php echo $this->url('zfcadmin/eportal-school', ['action' => 'manage']) ?>">Manage School</a></li>
    <li><a href="<?php echo $this->url('zfcadmin/eportal-session', ['action' => 'manage']) ?>">Manage Session</a></li>
</ul>