<?php
$this->headScript()->appendFile($this->basePath() . '/Eportal/lib/angular/angular.min.js', 'text/javascript')
        ->appendFile($this->basePath() . '/Eportal/module/property/service/PropertyService.js', 'text/javascript')
        ->appendFile($this->basePath() . '/Eportal/module/property/controller/PropertyController.js', 'text/javascript')
        ->appendFile($this->basePath() . '/Eportal/module/property/property.js', 'text/javascript');

$form = $this->loginForm;
$propertyFieldset = $form->get('eportal_property');
$form->prepare();
?>
<div class="page-header">
    <div class="container-fluid">
        <h1>Sign In</h1>
    </div>
</div>
<div class="container-fluid" ng-app="Eportal.property">
    <?php
    echo $this->formNg()->openTag($form, null, array('class' => 'form-horizontal'));
    ?>
    <div class="form-group">
        <label class="control-label col-sm-2">Registration Number</label>
        <div class="col-sm-10">
            <?php
            $identity = $form->get('identity');
            echo $this->formTextNg($identity, null, array('class' => 'form-control'));
            ?>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-sm-2">Password</label>
        <div class="col-sm-10">
            <?php
            $password = $form->get('credential');
            echo $this->formPasswordTwb($password, 'password', array('class' => 'form-control'));
            ?>
        </div>
    </div>
    <?php echo $this->partial('eportal-property/property_form.phtml', ['propertyFieldset' => $propertyFieldset]); ?>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <?php 
            $submit = $form->get('submit');
            $submit->setAttribute('value', 'Sign in');
            echo $this->formSubmitNg($submit, 'button', array('class' => 'btn-sm btn-success')); ?>
        </div>
    </div>
    <?php if ($this->redirect): ?>
        <input type="hidden" name="redirect" value="<?php echo $this->redirect ?>">
    <?php endif ?> 
    <?php echo $this->formNg()->closeTag(); ?>
</div>
