<ul>
    <li>
        Manage Class
        <ul>
            <li><a href="<?php echo $this->url('zfcadmin/eportal-class-user', ['user' => 'student']) ?>">Manage Class Students</a></li>
            <li><a href="<?php echo $this->url('zfcadmin/eportal-class-user', ['user' => 'teacher']) ?>">Manage Class Teachers</a></li>
        </ul>
    </li>
    <li>
        Manage Subjects
        <ul>
            <li><a href="<?php echo $this->url('zfcadmin/eportal-subject-user', ['user' => 'student']) ?>">Manage Subject Students</a></li>
            <li><a href="<?php echo $this->url('zfcadmin/eportal-subject-user', ['user' => 'teacher']) ?>">Manage Subject Teachers</a></li>
        </ul>
    </li>
    <li>
        School
        <ul>
            <li><a href="<?php echo $this->url('zfcadmin/eportal-school-user', ['user' => 'student']) ?>">View School Students</a></li>
            <li><a href="<?php echo $this->url('zfcadmin/eportal-school-user', ['user' => 'teacher']) ?>">View School Teachers</a></li>
        </ul>
    </li>
    <li>
        Department
        <ul>
            <li><a href="<?php echo $this->url('zfcadmin/eportal-department-user', ['user' => 'student']) ?>">View Department Students</a></li>
            <li><a href="<?php echo $this->url('zfcadmin/eportal-department-user', ['user' => 'teacher']) ?>">View Department Teachers</a></li>
        </ul>
    </li>
    <li>
        Session and Term
        <ul>
            <li><a href="<?php echo $this->url('zfcadmin/eportal-session-user', ['user' => 'student']) ?>">View Students</a></li>
            <li><a href="<?php echo $this->url('zfcadmin/eportal-session-user', ['user' => 'teacher']) ?>">View Teachers</a></li>
        </ul>
    </li>
</ul>