<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'EportalUser\Module'                        => __DIR__ . '/Module.php',
    'EportalUser\Controller\EportalUserController' => __DIR__ . '/src/EportalUser/Controller/EportalUserController.php',
    'EportalUserTest\Framework\TestCase'        => __DIR__ . '/tests/EportalUser/Framework/TestCase.php',
    'EportalUserTest\SampleTest'                => __DIR__ . '/tests/EportalUser/SampleTest.php',
);
