<?php
$property_values = $this->property_values;
$property = $this->escapeHtml($this->property);
$this->headTitle(ucwords($property));
?>
<div class="page-header">
    <div class="container-fluid">
        <h1 class="text-capitalize"><?php echo $property?></h1>
        <div class="pull-right text-capitalize">
            <a href="<?php echo $this->url("zfcadmin/eportal-{$property}", ['action' => 'save']) ?>" class="btn btn-primary" data-toggle="tooltip" data-original-title="Add New">
                <i class="fa fa-plus"></i>
                Add <?php echo $property ?>
            </a>
        </div>
    </div>
</div>
<div class="container-fluid">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">
                <i class="fa fa-list"></i> List
            </h3>
        </div>
        <table class="table table-bordered table-hover">
            <tbody>
                <?php foreach ($property_values as $property_value): ?>
                    <tr>
                        <td class="text-capitalize">
                            <a href="<?php echo $this->url("zfcadmin/eportal-{$property}", ['action' => 'manage'], ['query' => ['pid' => $property_value->getId()]]) ?>">
                                <?php echo $this->escapeHtml($property_value->getValue()); ?>
                            </a>
                        </td>
                        <td class="text-right">
                            <a class="btn btn-primary btn-sm" data-toggle="tooltip" data-original-title="edit" title="" 
                               href="<?php echo $this->url("zfcadmin/eportal-{$property}", ['action' => 'save'], ['query' => ['pid' => $property_value->getId()]]) ?>">
                                <i class="fa fa-pencil"></i>
                            </a>
                            <a class="btn btn-danger btn-sm" data-toggle="tooltip" data-original-title="delete" title=""
                               href="<?php echo $this->url("zfcadmin/eportal-{$property}", ['action' => 'delete'], ['query' => ['pid' => $property_value->getId()]]) ?>">
                                <i class="fa fa-trash"></i>
                            </a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>