<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Property\Module'                        => __DIR__ . '/Module.php',
    'Property\Controller\SkeletonController' => __DIR__ . '/src/Property/Controller/SkeletonController.php',
    'PropertyTest\Framework\TestCase'        => __DIR__ . '/tests/Property/Framework/TestCase.php',
    'PropertyTest\SampleTest'                => __DIR__ . '/tests/Property/SampleTest.php',
);
