<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'EportalSchool\Module'                        => __DIR__ . '/Module.php',
    'EportalSchool\Controller\EportalSchoolController' => __DIR__ . '/src/EportalSchool/Controller/EportalSchoolController.php',
    'EportalSchoolTest\Framework\TestCase'        => __DIR__ . '/tests/EportalSchool/Framework/TestCase.php',
    'EportalSchoolTest\SampleTest'                => __DIR__ . '/tests/EportalSchool/SampleTest.php',
);
