<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Eportal\Module'                        => __DIR__ . '/Module.php',
    'Eportal\Controller\EportalController' => __DIR__ . '/src/Eportal/Controller/EportalController.php',
    'EportalTest\Framework\TestCase'        => __DIR__ . '/tests/Eportal/Framework/TestCase.php',
    'EportalTest\SampleTest'                => __DIR__ . '/tests/Eportal/SampleTest.php',
);
