<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'EportalAdmin\Module'                        => __DIR__ . '/Module.php',
    'EportalAdmin\Controller\EportalAdminController' => __DIR__ . '/src/EportalAdmin/Controller/EportalAdminController.php',
    'EportalAdminTest\Framework\TestCase'        => __DIR__ . '/tests/EportalAdmin/Framework/TestCase.php',
    'EportalAdminTest\SampleTest'                => __DIR__ . '/tests/EportalAdmin/SampleTest.php',
);
