<div>
    <div>
        <h3>Student Details</h3>
    </div>
    <div>
    <table class="table table-condensed table-bordered">
        <tr>
            <td>Name</td>
            <td><?php echo $this->escapeHtml($this->student->fullname()); ?></td>
        </tr>
        <tr>
            <td>School</td>
            <td><?php echo $this->escapeHtml(ucwords($this->school->getValue())); ?></td>
        </tr>
        <tr>
            <td>Class</td>
            <td><?php echo $this->escapeHtml(($this->eportal_class->getValue())); ?></td>
        </tr>
        <?php if($this->section): ?>
            <tr>
                <td>Section</td>
                <td><?php echo $this->escapeHtml(ucwords($this->section->getValue())); ?></td>
            </tr>
            <?php endif; ?>
            <?php if($this->department): ?>
        <tr>
            <td>Department</td>
            <td><?php echo $this->escapeHtml(ucwords($this->department->getValue())); ?></td>
        </tr>
        <?php endif; ?>
        <tr>
            <td>Status</td>
            <td><?php echo $this->escapeHtml(ucwords($this->student->getStatus())); ?></td>
        </tr>
    </table>
    </div>
</div>