<?php
$users = $this->users;
$session = $this->session;
$term = $this->term;
?>
<div class="container-fluid">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title"><i class="fa fa-list"></i> List</h3>
        </div>
        <table class="table table-bordered table-hover">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Registration Number</th>
                    <th class="text-right">Actions</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($users as $user) { ?>
                    <tr>
                        <td class="text-capitalize"><a href="<?php echo $this->url('zfcadmin/user/view', ['id' => $user['id'], 'action' => 'index'], ['query' => ['session' => $session, 'term' => $term]]) ?>"><?php echo $user['fullname'] ?></a></td>
                        <td><?php echo $user['username'] ?></td>
                        <td class="text-right"><a href="<?php echo $this->url('zfcadmin/user/edit', [], ['query' => ['uid' => $user['id']]]) ?>" 
                               data-toggle="tooltip" data-original-title="edit" title="" 
                               class="btn btn-primary"><i class="fa fa-pencil"></i></a></td>
                    </tr>
                <?php } ?>
            </tbody>
        </table>
    </div>
</div>